### PR TITLE
Short-hand to get existing child

### PR DESCRIPTION
**Pull request by Aethelflaed**
Hi,

First of all, thanks for the great crate!

I often have to touch a path before using it for a current project, so I added this short-hand to my project and then copied it over for this PR.

I kept it simple and didn't bother with trying to create the parent folder or adding a variant like `existing_child_dir`

Tell me what you think

### CODE REVIEW

**Comment by epage** [comment]
So if I understand correctly, this allows you to `touch` a file while getting the path, allowing you to turn two lines into one?

I'm a little uncertain about case and the naming.

**Comment by Aethelflaed** [comment]
Yeah it's just a shorthand for something I have to do dozen of times per file, but nothing groundbreaking.

I'm still new to rust coming from ruby, so I'm used to libraries being shipped with plenty of convenience functions, but maybe that's not the way it's done amongst rustaceans?

If that's the case, let me know or feel free to directly close here

About the naming, yeah I'm not 100% happy about it either, but I preferred to validate the idea with you before spending time on the naming (it's good enough for my personal need)

**Comment by epage** [comment]
For me, whether to add something is a combination of the impact and how well it fits within the existing model.  The impact seems low and the hard naming suggests it might not fit within the existing model.

For Rust, there is more of a cost for every new feature added and a strong adherence to backwards compatibility that make me want to limit what I add to a widely used package.

**Comment by Aethelflaed** [comment]
Fair enough, thanks for the feedback

**Pull request closed without merging**
